version: '3'
services:
  proxy:
    build: ./
    networks:
      - ghost
      - hardikspace
    ports:
      - 80:80

networks:
  ghost:
    external:
      name: ghost_default
  hardikspace:
    external:
      name: hardikspace_default
